name: Copybara

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  WORKFLOW: archcenter

jobs:
  copybara:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
             
      - name: clone copybara
        run: git clone --depth=1 https://github.com/jvincent-mongodb/copybara-google
      
      - name: build copybara
        run: cd copybara-google && docker build -t google/copybara .

      - name: run copybara
        run: cd .github/workflows && ./run-copybara.sh
        