name: Copybara

on: [push]

jobs:
  copybara:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: clone copybara
        with:
          GH_TOKEN: somerandomtoken #${{ secrets.GH_TOKEN }}
          WORKFLOW: "cloud-docs"
        run: git clone --depth=1 https://github.com/google/copybara
      
      - name: build copybara
        run: cd copybara && docker build -t google/copybara .

      - name: run copybara
        run: cd .github/workflows && ./run-copybara.sh
        
