name: Copybara

on: [push]

jobs:
  copybara:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set env
        run: echo "GH_TOKEN=$(echo ${{ secrets.GH_TOKEN }} | sed 's/"/\\"/g'" >> $GITHUB_ENV && \
             echo "WORKFLOW=cloud-docs" >> $GITHUB_ENV
             
      - name: clone copybara
        run: git clone --depth=1 https://github.com/google/copybara
      
      - name: build copybara
        run: cd copybara && docker build -t google/copybara .

      - name: run copybara
        run: cd .github/workflows && ./run-copybara.sh
        
